# Generated by Django 5.1.3 on 2025-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=0, max_length=11, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
