# Generated by Django 5.1.3 on 2025-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='unknown', max_length=100, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
    ]
