# Generated by Django 5.1.3 on 2025-12-04 18:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('p', 'درصدی'), ('fa', 'مبلغ ثابت')], default='p', max_length=2, verbose_name='نوع تخفیف')),
                ('code', models.CharField(max_length=100, verbose_name='کدتخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مقدار تخفیف')),
                ('min_order_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='حداقل مبلغ قابل استفاده')),
                ('valid_from', models.DateTimeField(blank=True, verbose_name='تاریخ شروع اعتبار')),
                ('valid_to', models.DateTimeField(blank=True, verbose_name='تاریخ پایان اعتبار')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DF', 'فعال'), ('PB', 'تبدیل شده'), ('RJ', 'حذف شده')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='جمع مبلغ')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان اخرین تغییر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='سبدخریدها')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_carts', to='cart.coupon', verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'سبدخرید',
                'verbose_name_plural': ' سبدخریدها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت فعلی')),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='جمع مبلغ')),
                ('added_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ اضافه شدن سبد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='آیتم ها')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='ایتم های سبدخرید')),
            ],
            options={
                'verbose_name': 'آیتم سبدخرید',
                'verbose_name_plural': 'آیتم های سبدخرید',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ اضافه شدن به علاقه مندی ها')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محصول مورد علاقه',
                'verbose_name_plural': 'محصولات موردعلاقه',
                'ordering': ['-added_at'],
            },
        ),
    ]
