# Generated by Django 5.1.3 on 2025-12-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='satus',
            new_name='status',
        ),
    ]
