# Generated by Django 5.1.3 on 2025-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_satus_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش'),
        ),
    ]
