# Generated by Django 5.1.3 on 2025-12-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'ایجاد شده'), ('PendingPayment', ' در انتظار پرداخت'), ('Paid', 'پرداخت شده'), ('Processing', 'در حال پردازش'), ('Shipped', ' ارسال شده'), ('Delivered', ' تحویل داده شده'), ('Canceled', ' لغو شده'), ('Returned', 'مرجوع شده'), ('Failed', 'پرداخت ناموفق')], default='Created', max_length=50, verbose_name='وضعیت پرداخت'),
        ),
    ]
