# Generated by Django 5.1.3 on 2025-12-04 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='ـوضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name=' قیمت پایه')),
                ('discount_price', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('stock', models.IntegerField(verbose_name='موجودی انبار')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='کد محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d', verbose_name='عکس محصول')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
